<?php

// autoload.php @generated by Composer

// require_once __DIR__ . '/composer/autoload_real.php';
require __DIR__ . '../vendor/autoload.php';
return ComposerAutoloaderInit90540dd17ebe7f243ba332e3644d1c22::getLoader();
